name: 'hidden_minds'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths:    ["models"]
analysis-paths: ["analyses"]
test-paths:     ["tests"]
seed-paths:     ["seeds"]
macro-paths:    ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  +transient: false
  hidden_minds:
    staging:
      +materialized: view
      +database: "{{ env_var('DBT_ENVIRONMENTS', 'FAIL') }}_SILVER_DB"
      hidden_minds:
        +schema: hidden_minds
    marts:
      +materialized: table
      +database: "{{ env_var('DBT_ENVIRONMENTS', 'FAIL') }}_GOLD_DB"
      core:
        +schema: core

seeds:
  +schema: hidden_minds
  +database: "{{ env_var('DBT_ENVIRONMENTS', 'FAIL') }}_BRONZE_DB"


snapshots:
  +transient: false
  +target_database: "{{ env_var('DBT_ENVIRONMENTS', 'FAIL') }}_SILVER_DB"
  +target_schema: snapshots

tests:
  +store_failures: false
  +severity: error

